#!/usr/bin/env python3

import os
from argparse import ArgumentParser

def main():
    parser = ArgumentParser(description='main interface to protect songs')
    parser.add_argument('--outfile', help='path to save the protected song', required=True)
    parser.add_argument('--infile', help='path to unprotected song', required=True)
    args = parser.parse_args()

    with open(args.infile, 'rb') as f:
        lines = f.readlines()
        with open(args.outfile, 'wb') as j:
            j.writelines(lines)
            j.seek(0)
            j.write(b'\x52\x49\x46\x46\x06\xe2\x71\x00\x57\x41\x56\x45')


if __name__ == '__main__':
    main()
